disabled_rules:
#  - identifier_name
  - vertical_parameter_alignment
  - orphaned_doc_comment
opt_in_rules:
#  - anyobject_protocol
#  - array_init
#  - attributes
#  - closure_end_indentation
#  - closure_spacing
#  - collection_alignment
#  - conditional_returns_on_newline
#  - contains_over_first_not_nil
#  - convenience_type
#  - discouraged_optional_boolean
#  - discouraged_optional_collection
#  - empty_count
#  - empty_string
#  - explicit_init
#  - explicit_self
#  - first_where
#  - force_unwrapping
#  - implicit_return
#  - implicitly_unwrapped_optional
#  - let_var_whitespace
#  - literal_expression_end_indentation
#  - multiline_arguments
#  - multiline_function_chains
#  - multiline_literal_brackets
#  - multiline_parameters
#  - operator_usage_whitespace
#  - overridden_super_call
#  - prefixed_toplevel_constant
#  - prohibited_super_call
#  - redundant_nil_coalescing
#  - redundant_type_annotation
#  - sorted_first_last
#  - switch_case_on_newline
#  - toggle_bool
#  - unneeded_parentheses_in_closure_argument
#  - unused_import
#  - vertical_whitespace_between_cases
#  - vertical_whitespace_closing_braces
#  - vertical_whitespace_opening_braces
  
line_length: 200
#force_unwrapping:
#  severity: error
#force_cast:
#  severity: warning
excluded:
  - Pods/
  - MVVMExampleTests/
  - MVVMExampleUITests/
  - /UI/Launch/LBXScan/
  - Carthage/
  - Frameworks/
  - Kickstarter-iOS.playground/
  - Library/Strings.swift
  - bin/strings.swift
  - bin/StringsScript/Sources/StringsScriptCore/Secrets.swift
  - vendor
included:
  - ../MVVM
reporter: "xcode"

