# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'MVVMExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMExample
  pod 'MVVM', :path => '../'
  pod 'SwiftyJSON'
#  pod 'SwiftLint'

  target 'MVVMExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'RxTest'
    pod 'XCGLogger'
    pod 'SwiftDate'
  end
  
  target 'MVVMExampleUITests' do
    # Pods for testing
  end
  
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
end
