# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'MVVMExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMExample
  pod 'MVVM', :path => '../'
  pod 'SwiftyJSON'

  target 'MVVMExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMExampleUITests' do
    # Pods for testing
  end

end
