name: CI

on:
  push:
    branches:
        - master
  
  pull_request:
    branches:
        - master
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
          
  Test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: List available devices
        run: xcrun simctl list
      - name: Select Xcode
        run: sudo xcode-select -switch
            /Applications/Xcode_12.4.app &&
            /usr/bin/xcodebuild -version
      - name: Install Dependencies
        working-directory: ./MVVMExample
        run: pod install
      - name: Run unit tests
        run: xcodebuild clean test -workspace 'MVVMExample/MVVMExample.xcworkspace' 
            -scheme 'MVVMExample' -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=latest'
            -only-testing "MVVMExample/MVVMExampleTests"
            test-without-building | xcpretty && exit ${PIPESTATUS[0]}


